

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- name: Deploykubemanifests01
  value: kube  

stages:
  - stage: Deploy
    displayName: Deploystage
    jobs:
      - job: Deploykubemanifests01
        steps:
          
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/01-Webserver-Apps/'
              artifact: '01-Webserver-Apps'
              publishLocation: 'pipeline'
